#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2016
# Takashi Toyoshima <toyoshim@gmail.com>
#
# SPED-License-Identifier:	GPL-2.0+

obj-y	:= versatile.o
obj-y	+= lowlevel_init.o
